/*
 * This source file was generated by the Gradle 'init' task
 */
package stockmarket;

import stockmarket.view.SwingApp;

public class App {
    public static void main(String[] args) {
        SwingApp.main(args);
    }
}
